### ISSUE TITLE
Unexpected EOF in archive for rgb__taskonomy__mosquito.tar

### ISSUE THREAD

**Issue by ykarmesh** [EPFL-VILAB/omnidata-paper-code-dump#2]
I have been trying to download the rgb images from the omnidataset but I am getting the following error after hours of running the command:
### **Command**
```
omnitools.download rgb --components replica taskonomy gso_in_replica hypersim blendedmvs hm3d --subset fullplus --dest ./omnidata_starter_dataset/ --agree_all 
```
### **Error**
```
[DL:169MiB][#4fea77 3.4GiB/3.5GiB(97%)][#dbef2d 3.3GiB/4.6GiB(72%)][#536be6 2.8GiB/4.6GiB(61%)][#00df5a 2.3GiB/5.4GiB(43%)][#dacc02 1.9GiB/1.9GiB(99%)](+8) [FileAlloc:#aa89c3 1.0GiB/1.6GiB(64%)](+1)[NOTICE] "./omnidata_starter_dataset/rgb/taskonomy/milford" already exists... skipping
 66%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 367/555 [1:52:18<57:31, 18.36s/it]
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/omnidata_tools/dataset/download.py", line 244, in process_model
    raise e
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/omnidata_tools/dataset/download.py", line 240, in process_model
    untar(tar_fpath, dest=dest, model=model, ignore_existing=True, dryrun=dryrun)
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/omnidata_tools/dataset/download.py", line 167, in untar
    tar.extractall(path=tmpdirname)
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/tarfile.py", line 2028, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/tarfile.py", line 2069, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/tarfile.py", line 2141, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/tarfile.py", line 2190, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/tarfile.py", line 249, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/home/karmeshyadav/.conda/envs/omnidata/bin/omnitools.download", line 8, in <module>
    sys.exit(download())
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/fastcore/script.py", line 112, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/omnidata_tools/dataset/download.py", line 250, in download
    r = list(tqdm.tqdm(p.imap(process_model, models), total=len(models)))
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/private/home/karmeshyadav/.conda/envs/omnidata/lib/python3.8/site-packages/multiprocess/pool.py", line 868, in next
    raise value
tarfile.ReadError: unexpected end of data

11/08 22:42:58 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.
(omnidata) karmeshyadav@<Machine_Name>/<data_path>/karmeshyadav $
11/08 22:42:58 [NOTICE] Download GID#4fea776962bf265d not complete: compressed//rgb__taskonomy__natural.tar

11/08 22:42:58 [NOTICE] Download GID#dbef2dd54e3bbffd not complete: compressed//rgb__taskonomy__okabena.tar

11/08 22:42:58 [NOTICE] Download GID#536be66590ddca88 not complete: compressed//rgb__taskonomy__ooltewah.tar

11/08 22:42:59 [NOTICE] Download GID#00df5a4f545e6929 not complete: compressed//rgb__taskonomy__orangeburg.tar

11/08 22:42:59 [NOTICE] Download GID#dacc02ef43db8b05 not complete: compressed//rgb__taskonomy__oriole.tar

11/08 22:42:59 [NOTICE] Download GID#cd86267354b99c82 not complete: compressed//rgb__taskonomy__ovalo.tar

11/08 22:43:00 [NOTICE] Download GID#6ab937c3efee3ea7 not complete: compressed//rgb__taskonomy__oyens.tar

11/08 22:43:00 [NOTICE] Download GID#8e835def6d3ad764 not complete: compressed//rgb__taskonomy__paige.tar

11/08 22:43:00 [NOTICE] Download GID#948f006cc7928c6f not complete: compressed//rgb__taskonomy__pamelia.tar

11/08 22:43:01 [NOTICE] Download GID#17f5ff926e9a127d not complete: compressed//rgb__taskonomy__parole.tar

11/08 22:43:01 [NOTICE] Download GID#253d2c9e2da08eb9 not complete: compressed//rgb__taskonomy__pasatiempo.tar

11/08 22:43:02 [NOTICE] Download GID#aa89c3443f799bab not complete: compressed//rgb__taskonomy__peacock.tar

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
4fea77|INPR|    12MiB/s|compressed//rgb__taskonomy__natural.tar
dbef2d|INPR|    12MiB/s|compressed//rgb__taskonomy__okabena.tar
536be6|INPR|    11MiB/s|compressed//rgb__taskonomy__ooltewah.tar
00df5a|INPR|    11MiB/s|compressed//rgb__taskonomy__orangeburg.tar
dacc02|INPR|    12MiB/s|compressed//rgb__taskonomy__oriole.tar
cd8626|INPR|    11MiB/s|compressed//rgb__taskonomy__ovalo.tar
6ab937|INPR|    12MiB/s|compressed//rgb__taskonomy__oyens.tar
8e835d|INPR|    11MiB/s|compressed//rgb__taskonomy__paige.tar
948f00|INPR|    11MiB/s|compressed//rgb__taskonomy__pamelia.tar
17f5ff|INPR|    11MiB/s|compressed//rgb__taskonomy__parole.tar
253d2c|INPR|    12MiB/s|compressed//rgb__taskonomy__pasatiempo.tar
aa89c3|INPR|       0B/s|compressed//rgb__taskonomy__peacock.tar

Status Legend:
(INPR):download in-progress.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```
I tried the same command twice, and faced the same issue both the times. Looking into the `compressed/` folder, I see there is a file `rgb__taskonomy__mosquito.tar` which can't be extracted even manually. Can you please take a look into the issue?

**Comment by alexsax** [comment]
Ah yes thanks for identifying the problem file. `mosquito` has always had a problematic RGB `.tar` file, even since the dataset's release. I think it should just be removed from Taskonomy (and hence, omnidata). ~I'll push a fix to pip.~

Edit: Fix pushed. You should be able to get it with `pip install --upgrade omnidata-tools`. This fix disallows certain problematic buildings from Taskonomy. Specifically, the buildings listed here: https://github.com/alexsax/omnidata-tools/blob/b3bd0cde0a4b95ad4b228b4aa06efd371f8c12cc/omnidata_tools/dataset/starter_dataset/component_datasets/taskonomy/__init__.py#L15

**Comment by ykarmesh** [comment]
Thanks @alexsax for looking into this so quickly! While trying to download the files again, I realized that the script downloads all the tar files again which is redundant for the files that have been already downloaded and uncompressed. It will be great if the script could check the folder structure before downloading.

**Comment by alexsax** [comment]
Good point--I've added it in. Beware that this 'caching' behavior as implemented won't check for completeness--just that the folder exists.
